### PR TITLE
Component: Support Bootstrap 4

### LINKED ISSUE #2130: Bootstrap 4 support needs to be tested
### Checklist for this issue
If your issue is about the regex used in `email` rule, please note that as of version 1.12.0 this plugin is using the same regular expression that the HTML5 specification suggests for browsers to use (https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address). We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider using a custom method.
In case you need to adjust the built-in validation regular expression patterns, please follow the documentation (http://jqueryvalidation.org/jQuery.validator.methods/).

### Subject of the issue
Bootstrap 4 support needs to be tested

### Your environment
1.17.0
* Chrome

### Steps to reproduce
jquery-validation/demo/bootstrap/index.html 
needs to use Bootstrap 4.0.0 to test for bootstrap 4 support

### Expected behaviour
jquery-validation/demo/bootstrap/index.html 
needs to use Bootstrap 4.0.0 to test for bootstrap 4 support

### Actual behaviour
jquery-validation/demo/bootstrap/index.html 
uses Bootstrap 3

### PR DESCRIPTION
**Pull request by vairamsvsjdo**
Optional Bootstrap4 support

Fixes #2130

### Checklist for this pull request
Existing tests must work

#### Description
The demo code for bootstrap requires change to Bootstrap 4 with Bootstrap 4 has reached stable.

Thank you!

### CODE REVIEW

**Comment by staabm** [comment]
Please add a separate demo instead of changing the existing one

**Comment by gwhenne** [comment]
Here are the classes which have to be changed in the sample:

`"help-block"` becomes `"invalid-feedback"`
`"has-error"` becomes `"is-invalid"`
`"has-success"` becomes `"is-valid"`

Other changes are needed to the sample:
- use the new Bootstrap URL (doh!)
- formatting of the HTML elements

**Comment by Arkni** [comment]
Hi @vairamsvsjdo and @gwhenne,

Could any of you create a new demo with Bootstrap v4 instead of updating the Boostrap v3 one? We don't want to replace that demo as there are still people using Boostrap v3 out there.

Thanks!

**Comment by Arkni** [comment]
Hi there,

I'm closing this PR in favor of #2173 which adds a new demo for Bootstrap v4.

Thanks @vairamsvsjdo for your contribution, though.

**Pull request closed without merging**
