### PR TITLE
Update core.js

### PR DESCRIPTION
**Pull request by robuuust**
fix for null reference exception

#### Description

Thank you!

### CODE REVIEW

**Comment by staabm** [comment]
thx for the PR. please describe your use case and show us why this change is required and how to reproduce your problem

**Comment by robuuust** [comment]
When using summernote editor (https://www.npmjs.com/package/summernote) we get an error on this line because string happens to be undefined. The escapeCssMeta is receiving an undefined input instead of a string value. This causes the entire page to crash resulting in a broken editor.
This extra null check solves this issue.

**Comment by staabm** [comment]
in my experience this kind of change only hides actual errors at the caller side.

If we dont have evidence this is usefull for a lot of upstream projects, I dont want to merge this.

**Comment by staabm** [comment]
likely you run into this problem, because the element beeing validated misses a `name` attribute

**Pull request closed without merging**
