### PR TITLE
PhonePK

### PR DESCRIPTION
**Pull request by Soorajabbasi**
This is additional J Query Validate method for Pakistani Cellular phone number not for landline number. it take 12 characters in following format 03XX-XXXXXXX. and you must add 03 at the beginning.

### CODE REVIEW

**Comment by Soorajabbasi** [comment]
When my will be added to the additional folder of Jquery Validate

**Comment by staabm** [comment]
Please add tests and make sure your file has proper .js extensions

**Comment by Soorajabbasi** [comment]
How to add Proper Extensions?

**Comment by staabm** [comment]
You just need to rename the file

**Comment by Arkni** [comment]
@Soorajabbasi 

```bash
git mv src/additional/PhonePK src/additional/PhonePK.js
```

Commit the changes and push them

**Pull request closed without merging**
