### PR TITLE
Core: guard against null & undefined values in required method

### PR DESCRIPTION
**Pull request by Arkni**
Ref #2049

### CODE REVIEW

**Comment by Arkni** [comment]
I don't think there is a way to test it without using the normalizer. But the normalizer will not return `undefined` or `null` until #2054 was merged.

I will update the tests of the other PR and merge it and then update this one to use the normalizer.

For now, I added a description to the commit describing the needs for this fix.

**Comment by staabm** [comment]
Merged the other pr, we can add the tests here

**Comment by Arkni** [comment]
We are good to go.

**Comment by Arkni** [comment]
I'm going to merge this for now.
Thanks for the review and for merging the other PR.

**Comment by staabm** [comment]
Awesome that our normalizer layer also turned out to be a good value-mocking test utility 😸

**Comment by Arkni** [comment]
Yes, and also I see (from Stackoverflow and here) that a lot of folks are using it and found it useful too.

Thanks :)

**Pull request merged**
