### PR TITLE
localization: adding "tel" and "pattern" string to "zh"

### PR DESCRIPTION
**Pull request by horans**
(added in the beginning of all strings.)

### CODE REVIEW

**Comment by staabm** [comment]
Please prepend the commit message with "Localisation:"

**Comment by horans** [comment]
these 2 strings is not included in other language files, so i am not sure this commit should be categorized as "localization".
anyway, edited.

**Comment by horans** [comment]
these 2 strings is not included in other language files, so i am not sure this commit should be categorized as "localization".
anyway, edited.

**Comment by staabm** [comment]
Wha do you think we need those strings when they are not part of other lang files?

**Comment by horans** [comment]
these two strings refer to the input's html5 feature. i used them in my project, at least.
in my opinion, all language file should include them, especially for the "pattern" string.

**Pull request closed without merging**
