### PR TITLE
Use https instead of http

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by staabm** [comment]
Thx for your PR. This changes look good, but doesnt merge cleanly right now.

I will take care of it when back on a real computer.

**Comment by Arkni** [comment]
@staabm
are you able to update/merge this? If not, I can make the changes and merge it myself, but want to give you a chance to carry it through.

**Comment by vanillajonathan** [comment]
Please merge it yourself.

**Comment by Arkni** [comment]
Fixed the merge conflict locally and squashed the commits into one 3c03198

Thanks @vanillajonathan for your contribution :)

**Comment by vanillajonathan** [comment]
Thanks for fixing the merge conflict and merging it. :)

**Pull request closed without merging**
