### PR TITLE
remove "required"-attribute from element when removing "required"-rule

### PR DESCRIPTION
**Pull request by ischas**
Since the "attributeRules"-method checks for the "required"-attribute of the element, this attribute has to be removed when removing the "required"-rule.

This addresses #1745.

### CODE REVIEW

**Comment by staabm** [comment]
I am not sure we should do this. since the lib did not add this required attribute, we shouldnt remove it IMO.

to be honest I think you should add the required rule using `$(element).rules('add','required')` when you rely on `$(element).rules('remove','required')` to remove it again.

**Comment by ischas** [comment]
You're right when you say that my supposed change isn't symmetric. I'd suggest to change my pull request so the required-attribute is added when adding the required-rule.

Then the behaviour would be equal to the "aria-required"-attribute.

**Comment by Arkni** [comment]
From my point of view, this lib shouldn't remove attributes added by the user.

>to be honest I think you should add the required rule using $(element).rules('add','required') when you rely on $(element).rules('remove','required') to remove it again.

:+1: to this.

**Comment by Arkni** [comment]
> I changed my pull request so the required-attribute is added when adding the required-rule.
> 
> Now the behaviour is equal to the "aria-required"-attribute.

In that case, you should fix the travis failure: https://travis-ci.org/jzaefferer/jquery-validation/builds/116632270#L193

**Comment by staabm** [comment]
> You're right when you say that my supposed change isn't symmetric. I changed my pull request so the required-attribute is added when adding the required-rule.

hehe, I didnt foresee that you would just add the attribute... ;-)

I am still not convinced we should add/remove the `required` attribute.
per https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-required_attribute ´required` and `aria-required` are identical in a html5 document.

In previous html versions there is no "required" attribute defined.

I have to think about this change in general..

**Comment by staabm** [comment]
@ischas I didnt meant you need to adjust this PR furhter... I have to think about the general idea of this change.

wouldnt it be possible for you to use `$(element).rules('add','required')` instead of rendering a `required` attribute? Is there a reason why you dont do that?

**Comment by ischas** [comment]
We are collaborating with a third company, which generates the HTML. In some circumstances the validation rules of fields change and our JavaScript is responsible for this (client-side) changes.

If you prefer not to merge my suggested changes I have to remove the required-attribute in my code.

If you change your mind you must help me to get travis happy. ;-)

**Comment by ischas** [comment]
> From my point of view, this lib shouldn't remove attributes added by the user.
In fact, at the moment the "aria-required"-attributes is removed by code even it was added by the user.

https://jsfiddle.net/ischas/6hnw855z/2/

**Comment by Arkni** [comment]
You're right. I didn't take that into consideration because this lib will add that attribute to a required element to make it possible for `Screen readers` to announce the element as `required`. And delete it when the `required` rule is removed by the user.

**Comment by Arkni** [comment]
We dropped support for `aria-required` attribute in #2012. And I still stand by the point made by @staabm in https://github.com/jquery-validation/jquery-validation/pull/1746#issuecomment-197790882 and my own that this lib should not remove attributes added by the developer.

As a result, if anyone want to remove the `required` rule alongside the `required` attribute, they should do so by doing:
```js
$(element).rules('remove', 'required');
$(element).removeAttr('required');
```

I will close this PR for now. Feel free to ask if you have followup questions.
Thanks for oppening this PR, though.

**Pull request closed without merging**
