### PR TITLE
Nis br method review

### PR DESCRIPTION
**Pull request by csmendonca**
I've changed some reviews like orientation by @Arkni.

I've removed some spaces then I've chanced creation of date the new method nisBr.

Thank you!

### CODE REVIEW

**Comment by Arkni** [comment]
@csmendonca,

By the way, you don't need to close a PR and create a new one with the new changes everytime a maintainer requested something. You can just do the changes and push your commit and they will be visible on the PR.

I recommend watching this ~38 minutes lessons from **Kent C. Dodds**, they are the best getting started on contributing to Open Source on GitHub: https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

And, thank you again for your contribution :)

**Comment by csmendonca** [comment]
Hi @Arkni,

Sorry about that, it's happing because that was my first contribution to Open Source on GitHub.
Thank you so much, I'll watch that video which you recommended.

**Comment by Arkni** [comment]
Ah ok. I didn't pay attention.

Congratulation on your first contribution and Good luck :)

**Comment by csmendonca** [comment]
Hi @Arkni,

Thank you :)

**Pull request merged**
