### PR TITLE
Core: Adding ability to not show validation messages when calling valid().

### PR DESCRIPTION
**Pull request by tdekoning**
This feature is very usefull for when you want to check if a field is valid without showing the user he/she has done something wrong.

### CODE REVIEW

**Comment by jcspader** [comment]
+1 
I created a function with some fields. In onChange event, I test those fields, and if is valid, it call other  function.
I searched and I found issue  #1220. I think is a good idea.
I don't like @staabm suggestion. I think is function the library give information, if is valid or not.

**Comment by Nettsentrisk** [comment]
It's a bit of a pain that valid() applies a call to validate(), meaning there's no way to easily check whether the form is valid after it has already been validated. I guess the only way to accomplish that right now is to access the validator.invalid object on the jQuery data attached to the form?

My use case: I'm hooking onto the submit event from some other script on a form that's being validated through jQuery validation. Now, I want to know within that code whether the form that's being submitted is valid or not.

If I call form.valid(), it will redo the validation that just happened due to the submit event, so it's doing the validation logic twice in a row just to check if it's valid...

I guess I would have to hook up a submitHandler to this instance of the form, but can I set that after the validate-setup has already been run? Hmm.

**Comment by Arkni** [comment]
> I guess the only way to accomplish that right now is to access the validator.invalid object on the jQuery data attached to the form?

You shouldn't use internal variables, those may change from version to another which will cause your code to break. As an alternative, there are some internal methods that you can use:
* `validator.numberOfInvalids()`: return the count of invalid elements in your form (only the validated ones).
* `validator.invalidElements()`: returns a jQuery array that contains the invalid elements (only the validated ones).

> I guess I would have to hook up a submitHandler to this instance of the form, but can I set that after the validate-setup has already been run? Hmm.

From [submitHandler's docs](http://jqueryvalidation.org/validate/#submithandler):
```
submitHandler (default: native form submit)
   Type: Function()
   Callback for handling the actual submit when the form is valid. Gets the form as the
   only argument. Replaces the default submit. The right place to submit a form via
   Ajax after it is validated.
```

**Comment by Nettsentrisk** [comment]
Yes, but can you set up a new submitHandler after the form has already been set up with a call to .validate()? Will .validate(options: { submitHandler: function() { new submithandler } }) only overwrite the previous submitHandler, or will it set all the other options back to default also?

For now I've solved this by setting a data attribute on the form and checking if it exists when I first set up the form with .validate() to provide the correct submitHandler, but that's not very flexible.

**Comment by Arkni** [comment]
> Yes, but can you set up a new submitHandler after the form has already been set up with a call to .validate()? Will .validate(options: { submitHandler: function() { new submithandler } }) only overwrite the previous submitHandler, or will it set all the other options back to default also?

The second call of `.validate( {} )` will be ignored by the plugin.
But I guess you can overwrite the submitHandler this way:
```js
var validator = $( "yourForm" ).data( "validator" );
validator.settings.submitHandler = function() {
    // new submitHandler
};
```

**Pull request closed without merging**
