### PR TITLE
Core: removed aria-required attribute

### PR DESCRIPTION
**Pull request by alexbokii**
According to the latest documentation, 'aria-required' is a widget attribute and should be used only with particular roles. We don’t need to use it with native elements and when ‘required’ attribute exist. At the moment all instances of 'aria-required' attribute cause an error "This element has an unsupported ARIA attribute" in Google Chrome accessibility validator.
https://www.w3.org/TR/wai-aria/states_and_properties#aria-required

This addresses #1841.

### CODE REVIEW

**Comment by Arkni** [comment]
@alexbokii 
Does the same apply to `contenteditable` elements like `div`s ?
What should happen in that case ?

**Comment by alexbokii** [comment]
@Arkni No, it's different when we use divs - we need to apply aria-required attribute if the div tag is used instead of the input tag and user input is required. But the div should have a role attribute that points to the nature of control - it can be a "textbox", "combobox", etc.
So, according to this doc - https://www.w3.org/TR/wai-aria/states_and_properties#attrs_widgets, if we want to use aria-required with divs we must also add a role:
`<div contenteditable="true" role="textbox" aria-required="true">`.

**Comment by staabm** [comment]
IIRC we support only real input types. When people use custom markup instead of native input elements they should apply the aria roles for them.

IMHO we should stop adding aria attributes.

👍

**Comment by Arkni** [comment]
@alexbokii 
Thanks a lot for your contribution :)

**Comment by alexbokii** [comment]
@Arkni happy to help :)

**Pull request merged**
